title: Renaissance Simulations Laboratory
email: matthewturk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Explore the first galaxies through physics-based modeling, simulation, and data exploration
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rensimlab.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  rensimlab
google_analytics: UA-132780020-3

# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-youtube

